# Generated by Django 6.0 on 2026-01-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extractionjob',
            old_name='completed_at',
            new_name='finished_at',
        ),
    ]
